{ inputs, lib, pkgs, ... }:
let
  # npinsPaths = lib.mapAttrsToList (
  #   k: v: lib.optionalString (lib.isAttrs v) "${k}=${v}"
  # ) (import ../npins);
in {
  android-integration = {
    termux-open.enable = true;
    termux-open-url.enable = true;
    termux-reload-settings.enable = true;
    termux-setup-storage.enable = true;
    xdg-open.enable = true;
  };

  # nix.nixPath = npinsPaths;

  build.activation = {
    #generateResolvConf = let
    #  path = "/etc/resolv.conf";
    #in /* bash */ ''
    #  echo "generating resolv.conf"
    #  $DRY_RUN_CMD printf "# Generated by nix-on-droid. Warning: changes will be overwritten #\n" > "${path}"
    #  $DRY_RUN_CMD printf "nameserver 1.1.1.1\n" >> "${path}"
    #  $DRY_RUN_CMD printf "nameserver 8.8.8.8\n" >> "${path}"
    #'';
    generateTermuxProperties = let
      path = "$HOME/.config/termux/termux.properties";
      settings = {
        fullscreen = true;
        use-fullscreen-workaround = true;
      };
    in /* bash */ ''
      echo "generating termux.properties"
      $DRY_RUN_CMD mkdir -p $(dirname ${path})
      $DRY_RUN_CMD printf "# Generated by nix-on-droid. Warning: changes will be overwritten #\n" > "${path}"
      $DRY_RUN_CMD printf "${lib.generators.toKeyValue {} settings}" >> "${path}"
    '';
  };

  home-manager = {
    config = ../home-manager/devices/nix-on-droid.nix;
    extraSpecialArgs = {
      inherit inputs;
      inherit pkgs;
    };
    # sharedModules = [
    #   inputs.nur.modules.homeManager.default
    # ];
  };
  system.stateVersion = "24.05";
}
