{ lib, pkgs, ... }:
let
  npinsPaths = lib.mapAttrsToList (k: v: "${k}=${v}") (import ../npins);
in {
  android-integration = {
    termux-open.enable = true;
    termux-open-url.enable = true;
    termux-reload-settings.enable = true;
    termux-setup-storage.enable = true;
    xdg-open.enable = true;
  };

  nix.nixPath = npinsPaths;

  build.activation.generateTermuxProperties = let
    path = "$XDG_CONFIG_HOME/termux/termux.properties";
    settings = {
      fullscreen = true;
      use-fullscreen-workaround = true;
    };
  in /* bash */ ''
    echo "generating termux.properties"
    $DRY_RUN_CMD mkdir -p $(dirname ${path})
    $DRY_RUN_CMD printf "# Generated by nix-on-droid. Warning: changes will be overwritten #\n" > "${path}"
    $DRY_RUN_CMD printf "${lib.generators.toKeyValue {} settings}" >> "${path}"
  '';

  home-manager.config = ../home-manager/home.nix;
  system.stateVersion = "21.11";
}
